---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    name: Building message on push
    environment: dev
    steps:
      - name: Run a one-line script
        uses: actions/checkout@v3
      - name: Making resource folder in src folder
        uses: mkdir src/main/resources
        
      - name: Generate application.properties
        run: |
          echo 'aws.accessKeyId==${{ secrets.ACCESSKEYID }}' >> src/main/resources/application.properties
          echo 'aws.secretAccessKey=${{ secrets.SECRETACCESSKEY }}' >> src/main/resources/application.properties
          echo 'aws.region=${{ secrets.REGION }}' >> src/main/resources/application.properties
          echo 'spring.application.name=$APPNAME' >> src/main/resources/application.properties
          echo 'contactUsTable=$CONTACTUSTABLE' >> src/main/resources/application.properties
          echo 'contactustopicArn=$CONTACTUSTOPICARN' >> src/main/resources/application.properties
      - name: Set up java 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
      - name: Build with Maven
        run: mvn clean install
